services:
  - type: web
    name: macro-fed-bce
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application -c gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
